#mark Tribe 

- type: loadout
  id: N14ClothingHeadHatTribalPowerhelm
  category: Head
  cost: 8
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
  items:
    - N14ClothingHeadHatTribalPowerhelm

- type: loadout
  id: N14TribalSword
  category: Weapons
  cost: 4
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutMelee
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14TribalSword
