#mark Tribe 

- type: loadout
  id: N14ClothingHeadHatTribalPowerhelm
  category: Head
  cost: 3
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
    - !type:CharacterPlaytimeRequirement
      tracker: TribalElder
      min: 36000 # 10 hours veterancy unlock
  items:
    - N14ClothingHeadHatTribalPowerhelm

- type: loadout
  id: N14TribalSword
  category: Weapons
  cost: 4
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutMelee
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14TribalSword

- type: loadout
  id: N14ClothingOuterElderwintercoat
  category: N14LoadoutOuter
  cost: 0
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
  items:
    - N14ClothingOuterElderwintercoat
