#mark Tribe 

- type: loadout
  id: N14ClothingHeadHatTribalPowerhelm
  category: Head
  cost: 3
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
    - !type:CharacterPlaytimeRequirement
      tracker: TribalElder
      min: 36000 # 10 hours veterancy unlock
  items:
    - N14ClothingHeadHatTribalPowerhelm

- type: loadout
  id: N14TribalSword
  category: Weapons
  cost: 4
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutMelee
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14TribalSword

- type: loadout
  id: N14ClothingOuterElderwintercoat
  category: N14LoadoutOuter
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
  items:
    - N14ClothingOuterElderwintercoat

- type: loadout
  id: N14ClothingOuterdrylandelder
  category: N14LoadoutOuter
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
  items:
    - N14ClothingOuterdrylandelder

- type: loadout
  id: N14ClothingOuterBandito
  category: N14LoadoutOuter
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterBandito

- type: loadout
  id: N14ClothingOuterforager
  category: N14LoadoutOuter
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterforager

- type: loadout
  id: N14ClothingOuterheadtaker
  category: N14LoadoutOuter
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterheadtaker

- type: loadout
  id: N14ClothingOuterhunter
  category: N14LoadoutOuter
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterhunter

- type: loadout
  id: N14ClothingOuterponcho
  category: N14LoadoutOuter
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterponcho

- type: loadout
  id: N14ClothingOutershaman
  category: N14LoadoutOuter
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOutershaman

- type: loadout
  id: N14ClothingOuterdrylandersimple
  category: N14LoadoutOuter
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterdrylandersimple
